# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('permission', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('backgroundImgUrl', models.URLField(default='')),
                ('deadline', models.DateTimeField()),
                ('content', models.TextField()),
                ('enabled', models.BooleanField(default=False)),
                ('user', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SignUpUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('signUp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HYauth.SignUp')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('studentId', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=32)),
                ('department', models.IntegerField(default=-1)),
                ('department_position', models.IntegerField(default=-1)),
                ('phone', models.IntegerField()),
                ('major', models.CharField(max_length=64)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HYauth.Role')),
            ],
        ),
        migrations.AddField(
            model_name='signupuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HYauth.User'),
        ),
        migrations.AddField(
            model_name='signup',
            name='applicant',
            field=models.ManyToManyField(through='HYauth.SignUpUser', to='HYauth.User'),
        ),
    ]
