# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HYauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentId',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
