# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HYauth', '0003_auto_20181102_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='permission',
            new_name='permissions',
        ),
    ]
