# Generated by Django 2.1.3 on 2018-11-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HYauth', '0005_auto_20181102_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_hash',
            field=models.CharField(max_length=32),
        ),
    ]
