# Generated by Django 2.1.3 on 2018-11-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HYauth', '0006_auto_20181102_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentId',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
