# Generated by Django 2.1.3 on 2018-11-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HYauth', '0007_auto_20181102_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_class',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='department_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.IntegerField(default=0),
        ),
    ]
