# Generated by Django 2.1.3 on 2018-11-03 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HYauth', '0008_auto_20181102_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='signupuser',
            name='signUp',
        ),
        migrations.RemoveField(
            model_name='signupuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
        migrations.DeleteModel(
            name='SignUpUser',
        ),
    ]
