# Generated by Django 2.1.3 on 2018-11-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HYauth', '0009_auto_20181103_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_class',
            new_name='class_room',
        ),
    ]
