# Generated by Django 2.1.3 on 2018-11-03 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HYauth', '0009_auto_20181103_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('backgroundImgUrl1', models.URLField(default='')),
                ('backgroundImgUrl2', models.URLField(default='')),
                ('deadline', models.DateTimeField()),
                ('content', models.TextField()),
                ('enabled', models.BooleanField(default=False)),
                ('user', models.CharField(max_length=64)),
                ('applicant', models.ManyToManyField(to='HYauth.User')),
            ],
        ),
    ]
