# Generated by Django 2.1.3 on 2018-11-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0002_auto_20181103_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
