# Generated by Django 2.1.3 on 2018-11-03 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0003_auto_20181103_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
