# Generated by Django 2.1.3 on 2018-11-03 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0004_auto_20181103_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, default='', upload_to='signUp/background/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='signup',
            name='backgroundImgUrl1',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='backgroundImgUrl2',
        ),
        migrations.AddField(
            model_name='banner',
            name='signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signUp.SignUp'),
        ),
    ]
