# Generated by Django 2.1.3 on 2018-11-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0007_auto_20181103_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
